export const FETCH_USER_CART = "FETCH_USER_CART";
export const FETCH_USER_CART_SUCCESS = "FETCH_USER_CART_SUCCESS";
export const FETCH_USER_CART_FAILED = "FETCH_USER_CART_ERROR";


export const INCREASE_QUANTITY = "INCREASE_QUANTITY";
export const DECREASE_QUANTITY = "DECREASE_QUANTITY";
export const UPDATE_QUANTITY_FAILED = "UPDATE_QUANTITY_FAILED";