export const GET_CHECKOUT_SESSION = "GET_CHECKOUT_SESSION";
export const GET_CHECKOUT_SESSION_SUCCESS = "GET_CHECKOUT_SESSION_SUCCESS";
export const GET_CHECKOUT_SESSION_FAILED = "GET_CHECKOUT_SESSION_FAILED";